sudo: false
language: scala
addons:
  apt:
    packages:
      - nodejs
install: true # disable travis' default mvn install before running the tests
scala:
  - "2.10.4"
jdk:
  - openjdk7
script: mvn clean verify package
cache:
  directories:
    - $HOME/.m2/repository
