sudo: false
language: scala
node_js:
  - "6"
install: true # disable travis' default mvn install before running the tests
scala:
  - "2.11.2"
jdk:
  - oraclejdk8
script: mvn clean test package
cache:
  directories:
    - $HOME/.m2/repository
