language: scala
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y nodejs
install: true # disable travis' default mvn install before running the tests
scala:
  - "2.10.2"
jdk:
  - openjdk6
script: mvn clean test package
